services:
  app:
    image: putri123/myapp:latest
    container_name: iot-lampu-app
    restart: unless-stopped

    ports:
      - "8080:8080"

    env_file:
      - .env

    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    container_name: iot-lampu-mariadb
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: